# routers/items.py — Generated by VIA

from fastapi import APIRouter, HTTPException
from typing import List, Optional
from datetime import datetime

router = APIRouter()

# In-memory store — works without any database setup
_items: dict = {}
_counter: int = 0


@router.get("/items")
async def list_items(skip: int = 0, limit: int = 100):
    items = list(_items.values())
    return {"items": items[skip: skip + limit], "total": len(items)}


@router.post("/items", status_code=201)
async def create_item(item: dict):
    global _counter
    _counter += 1
    record = {
        "id":          _counter,
        "created_at":  datetime.utcnow().isoformat(),
        **item
    }
    _items[_counter] = record
    return record


@router.get("/items/{item_id}")
async def get_item(item_id: int):
    if item_id not in _items:
        raise HTTPException(status_code=404, detail="Item not found")
    return _items[item_id]


@router.put("/items/{item_id}")
async def update_item(item_id: int, updates: dict):
    if item_id not in _items:
        raise HTTPException(status_code=404, detail="Item not found")
    _items[item_id].update(updates)
    _items[item_id]["updated_at"] = datetime.utcnow().isoformat()
    return _items[item_id]


@router.delete("/items/{item_id}")
async def delete_item(item_id: int):
    if item_id not in _items:
        raise HTTPException(status_code=404, detail="Item not found")
    del _items[item_id]
    return {"deleted": True, "id": item_id}


@router.get("/stats")
async def get_stats():
    return {
        "total":  len(_items),
        "active": sum(1 for i in _items.values() if i.get("status") == "active"),
    }